name: Workflow template
run-name:  ${{ format('Workflow template {0} {1} {2}', 'Mona', 'the', 'Octocat') }}
on:
  workflow_dispatch:
    inputs:
      msg:
        description: "message:"
        default: "Hello World!"
        required: true

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      arch: ${{ github.event.inputs.msg }}
    strategy:
      fail-fast: false
      matrix:
        target_arch: [matrix0, matrix1]

    steps:
      - uses: actions/checkout@main
      - name: Checkout repository and print enviroment
        shell: bash {0}
        env:
          PACKAGE_VARIANT: ${{ matrix.target_arch }}
        run: |
          env
          cat /proc/cpuinfo
          tree -L 2 ${GITHUB_WORKSPACE}

          heredoc(){
            cat <<EOF
          heredoc_content
          EOF

            cat <<EOF
            heredoc_content
          EOF

            cat <<-EOF
          heredoc_content
          EOF

          cat <<-EOF
            heredoc_content
          EOF
          }

          heredoc

      - name: Create files
        run: |
          echo "echo hello world" > echo_hello
          chmod +x echo_hello
          tar -c echo_hello | xz -T0 > echo_hello.tar.xz

      - name: Upload
        uses: actions/upload-artifact@main
        with:
          name: echo_hello
          path: echo_hello.tar.xz